temp_dir: '/tmp/'
segment_prefix: 'sample'
index_prefix: 'stream'

# type of logging: STDOUT, FILE
log_type: 'STDOUT'
#log_type: 'FILE'
#log_file: '/tmp/streamer.log'
# levels: DEBUG, INFO, WARN, ERROR
log_level: 'DEBUG'

# where the origin video is going to come from
#input_location: '-'
input_location: '/tmp/test.avi'

# segment length in seconds
segment_length: 10 

# this is the URL where the stream (ts) files will end up
# if this location is the same as the location where the m3u8 
# index is then leave it blank
url_prefix: 

# how many segments to keep in the index
index_segment_count: 15

# this command is used for multirate encodings and is what pushes the encoders
source_command: 'cat %s'

# This is the location of the segmenter
segmenter_binary: './live_segmenter'

# the encoding profile to use
encoding_profile: [ 'cell_4x3_150k', 'cell_4x3_240k', 'cell_4x3_440k', 'wifi_4x3_640k', 'wifi_4x3_840k', 'wifi_4x3_1240k' ]

# The upload profile to use
transfer_profile: 'copy_dev'

#
# Encoding profiles
#
cell_4x3_150k: 
  ffmpeg_command: "ffmpeg -er 4 -i %s -f mpegts -acodec libmp3lame -ar 32000 -ab 48k -s 400x300 -vcodec libx264 -b 110k -flags +loop+mv4 -cmp 256 -partitions +parti4x4+partp8x8+partb8x8 -subq 7 -trellis 1 -refs 5 -coder 0 -me_range 16 -keyint_min 25 -sc_threshold 40 -i_qfactor 0.71 -bt 110k -maxrate 110k -bufsize 110k -rc_eq 'blurCplx^(1-qComp)' -qcomp 0.6 -qmin 10 -qmax 51 -qdiff 4 -level 30 -aspect 4:3 -r 10 -g 30 -async 2 - | %s %s %s %s %s"
  bandwidth: 158000

cell_4x3_240k: 
  ffmpeg_command: "ffmpeg -er 4 -i %s -f mpegts -acodec libmp3lame -ar 32000 -ab 48k -s 400x300 -vcodec libx264 -b 200k -flags +loop+mv4 -cmp 256 -partitions +parti4x4+partp8x8+partb8x8 -subq 7 -trellis 1 -refs 5 -coder 0 -me_range 16 -keyint_min 25 -sc_threshold 40 -i_qfactor 0.71 -bt 200k -maxrate 200k -bufsize 200k -rc_eq 'blurCplx^(1-qComp)' -qcomp 0.6 -qmin 10 -qmax 51 -qdiff 4 -level 30 -aspect 4:3 -r 15 -g 45 -async 2 - | %s %s %s %s %s"
  bandwidth: 248000

cell_4x3_440k: 
  ffmpeg_command: "ffmpeg -er 4 -i %s -f mpegts -acodec libmp3lame -ar 32000 -ab 48k -s 400x300 -vcodec libx264 -b 400k -flags +loop+mv4 -cmp 256 -partitions +parti4x4+partp8x8+partb8x8 -subq 7 -trellis 1 -refs 5 -coder 0 -me_range 16 -keyint_min 25 -sc_threshold 40 -i_qfactor 0.71 -bt 400k -maxrate 400k -bufsize 400k -rc_eq 'blurCplx^(1-qComp)' -qcomp 0.6 -qmin 10 -qmax 51 -qdiff 4 -level 30 -aspect 4:3 -r 30 -g 90 -async 2 - | %s %s %s %s %s"
  bandwidth: 448000

wifi_4x3_640k: 
  ffmpeg_command: "ffmpeg -er 4 -i %s -f mpegts -acodec libmp3lame -ar 32000 -ab 48k -s 640x480 -vcodec libx264 -b 600k -flags +loop+mv4 -cmp 256 -partitions +parti4x4+partp8x8+partb8x8 -subq 7 -trellis 1 -refs 5 -coder 0 -me_range 16 -keyint_min 25 -sc_threshold 40 -i_qfactor 0.71 -bt 600k -maxrate 600k -bufsize 600k -rc_eq 'blurCplx^(1-qComp)' -qcomp 0.6 -qmin 10 -qmax 51 -qdiff 4 -level 30 -aspect 4:3 -r 30 -g 90 -async 2 - | %s %s %s %s %s"
  bandwidth: 648000

wifi_4x3_840k: 
  ffmpeg_command: "ffmpeg -er 4 -i %s -f mpegts -acodec libmp3lame -ar 32000 -ab 48k -s 640x480 -vcodec libx264 -b 800k -flags +loop+mv4 -cmp 256 -partitions +parti4x4+partp8x8+partb8x8 -subq 7 -trellis 1 -refs 5 -coder 0 -me_range 16 -keyint_min 25 -sc_threshold 40 -i_qfactor 0.71 -bt 800k -maxrate 800k -bufsize 800k -rc_eq 'blurCplx^(1-qComp)' -qcomp 0.6 -qmin 10 -qmax 51 -qdiff 4 -level 30 -aspect 4:3 -r 30 -g 90 -async 2 - | %s %s %s %s %s"
  bandwidth: 848000

wifi_4x3_1240k: 
  ffmpeg_command: "ffmpeg -er 4 -i %s -f mpegts -acodec libmp3lame -ar 32000 -ab 48k -s 640x480 -vcodec libx264 -b 1200k -flags +loop+mv4 -cmp 256 -partitions +parti4x4+partp8x8+partb8x8 -subq 7 -trellis 1 -refs 5 -coder 0 -me_range 16 -keyint_min 25 -sc_threshold 40 -i_qfactor 0.71 -bt 1200k -maxrate 1200k -bufsize 1200k -rc_eq 'blurCplx^(1-qComp)' -qcomp 0.6 -qmin 10 -qmax 51 -qdiff 4 -level 30 -aspect 4:3 -r 30 -g 90 -async 2 - | %s %s %s %s %s"
  bandwidth: 1248000

#
# Transfer profiles
#
s3_dev:
  transfer_type: 's3'
  bucket_name: 'bucket'
  key_prefix: 'stream0001'
  aws_api_key: 'key'
  aws_api_secret: 'secret'

ftp_dev:
  transfer_type: 'ftp'
  remote_host: '192.168.1.1'
  user_name: 'user'
  password: 'pass'
  directory: 'html/streamingvideo'

scp_dev:
  transfer_type: 'scp'
  remote_host: '192.168.1.1.'
  user_name: 'root'
  #password: 'pass'
  directory: '/web/sites/test.com/html/streamingvideo'

copy_dev:
  transfer_type: 'copy'
  directory: '/var/www/html/streamingvideo'
